Repository OCA/stock-logistics-reporting, pull requests merged in 2020-12, with the labels that each got.

#127 [FIX][10.0]travis.yml
  .travis.yml
Labels: approved, bot is merging ⏳, ready to merge

#125 [ADD] stock_picking_report_valued_sale_mrp: New module
  stock_picking_report_valued_sale_mrp/README.rst
  stock_picking_report_valued_sale_mrp/__init__.py
  stock_picking_report_valued_sale_mrp/__manifest__.py
  stock_picking_report_valued_sale_mrp/models/__init__.py
  stock_picking_report_valued_sale_mrp/models/stock_move.py
  stock_picking_report_valued_sale_mrp/models/stock_move_line.py
  stock_picking_report_valued_sale_mrp/readme/CONTRIBUTORS.rst
  stock_picking_report_valued_sale_mrp/readme/DESCRIPTION.rst
  stock_picking_report_valued_sale_mrp/readme/ROADMAP.rst
  stock_picking_report_valued_sale_mrp/readme/USAGE.rst
  stock_picking_report_valued_sale_mrp/report/stock_picking_report_valued.xml
  stock_picking_report_valued_sale_mrp/static/description/index.html
  stock_picking_report_valued_sale_mrp/tests/__init__.py
  stock_picking_report_valued_sale_mrp/tests/test_stock_picking_report_valued_mrp.py
Labels: bot is merging ⏳

#129 [FIX] stock_picking_report_valued_sale_mrp: error when no sale line
  stock_picking_report_valued_sale_mrp/models/stock_move_line.py
Labels: approved, bot is merging ⏳
