Repository OCA/stock-logistics-reporting, pull requests merged in 2020-03, with the labels that each got.

#79 [12.0][ADD] stock_picking_product_label
  stock_picking_product_label/__init__.py
  stock_picking_product_label/__manifest__.py
  stock_picking_product_label/readme/CONTRIBUTORS.rst
  stock_picking_product_label/readme/DESCRIPTION.rst
  stock_picking_product_label/readme/USAGE.rst
  stock_picking_product_label/reports/report_print_labels.xml
  stock_picking_product_label/reports/report_print_labels_template.xml
Labels: needs review

#90 [12.0] porting stock_analysis
  setup/stock_analysis/odoo/addons/stock_analysis
  setup/stock_analysis/setup.py
  stock_analysis/__init__.py
  stock_analysis/__manifest__.py
  stock_analysis/i18n/it.po
  stock_analysis/readme/CONTRIBUTORS.rst
  stock_analysis/readme/DESCRIPTION.rst
  stock_analysis/report/__init__.py
  stock_analysis/report/stock_analysis.py
  stock_analysis/report/stock_analysis_view.xml
  stock_analysis/security/ir.model.access.csv
  stock_analysis/static/description/demo_analysis.png
  stock_analysis/static/description/icon.png
Labels: approved, migration, needs review, ready to merge

#77 [12.0][ADD] stock_card_report
  oca_dependencies.txt
  stock_card_report/README.rst
  stock_card_report/__init__.py
  stock_card_report/__manifest__.py
  stock_card_report/data/paper_format.xml
  stock_card_report/data/report_data.xml
  stock_card_report/readme/CONTRIBUTORS.rst
  stock_card_report/readme/DESCRIPTION.rst
  stock_card_report/readme/USAGE.rst
  stock_card_report/reports/__init__.py
  stock_card_report/reports/stock_card_report.py
  stock_card_report/reports/stock_card_report.xml
  stock_card_report/reports/stock_card_report_xlsx.py
  stock_card_report/static/description/icon.png
  stock_card_report/static/description/index.html
  stock_card_report/static/src/css/report.css
  stock_card_report/static/src/js/stock_card_report_backend.js
  stock_card_report/tests/__init__.py
  stock_card_report/tests/test_stock_card_report.py
  stock_card_report/wizard/__init__.py
  stock_card_report/wizard/stock_card_report_wizard.py
  stock_card_report/wizard/stock_card_report_wizard_view.xml
Labels: approved, needs review, ready to merge

#97 [13.0][MIG] stock_card_report
  oca_dependencies.txt
  stock_card_report/README.rst
  stock_card_report/__init__.py
  stock_card_report/__manifest__.py
  stock_card_report/data/paper_format.xml
  stock_card_report/data/report_data.xml
  stock_card_report/i18n/stock_card_report.pot
  stock_card_report/readme/CONTRIBUTORS.rst
  stock_card_report/readme/DESCRIPTION.rst
  stock_card_report/readme/USAGE.rst
  stock_card_report/reports/__init__.py
  stock_card_report/reports/stock_card_report.py
  stock_card_report/reports/stock_card_report.xml
  stock_card_report/reports/stock_card_report_xlsx.py
  stock_card_report/static/description/icon.png
  stock_card_report/static/description/index.html
  stock_card_report/static/src/css/report.css
  stock_card_report/static/src/js/stock_card_report_backend.js
  stock_card_report/tests/__init__.py
  stock_card_report/tests/test_stock_card_report.py
  stock_card_report/wizard/__init__.py
  stock_card_report/wizard/stock_card_report_wizard.py
  stock_card_report/wizard/stock_card_report_wizard_view.xml
Labels: approved, migration, needs review, ready to merge

#91 [MIG][13.0] stock_picking_report_valued: Migration to v13.0
  stock_picking_report_valued/README.rst
  stock_picking_report_valued/__init__.py
  stock_picking_report_valued/__manifest__.py
  stock_picking_report_valued/i18n/es.po
  stock_picking_report_valued/i18n/hr.po
  stock_picking_report_valued/i18n/stock_picking_report_valued.pot
  stock_picking_report_valued/models/__init__.py
  stock_picking_report_valued/models/res_partner.py
  stock_picking_report_valued/models/stock_move_line.py
  stock_picking_report_valued/models/stock_picking.py
  stock_picking_report_valued/readme/CONFIGURE.rst
  stock_picking_report_valued/readme/CONTRIBUTORS.rst
  stock_picking_report_valued/readme/DESCRIPTION.rst
  stock_picking_report_valued/readme/ROADMAP.rst
  stock_picking_report_valued/readme/USAGE.rst
  stock_picking_report_valued/report/stock_picking_report_valued.xml
  stock_picking_report_valued/static/description/icon.png
  stock_picking_report_valued/static/description/index.html
  stock_picking_report_valued/tests/__init__.py
  stock_picking_report_valued/tests/test_stock_picking_valued.py
  stock_picking_report_valued/views/res_partner_view.xml
Labels: approved, migration, needs review

#95 [12.0][IMP] stock_inventory_valuation_report: Reference and Barcode columns
  stock_inventory_valuation_report/i18n/stock_inventory_valuation_report.pot
  stock_inventory_valuation_report/reports/stock_inventory_valuation_report.py
  stock_inventory_valuation_report/reports/stock_inventory_valuation_report.xml
  stock_inventory_valuation_report/reports/stock_inventory_valuation_report_xlsx.py
Labels: approved, ready to merge
