Repository OCA/stock-logistics-reporting, pull requests merged in 2020-10, with the labels that each got.

#117 [12.0] [MIG] stock_move_value_report: Migration to v12.0
  stock_move_value_report/README.rst
  stock_move_value_report/__init__.py
  stock_move_value_report/__manifest__.py
  stock_move_value_report/i18n/es.po
  stock_move_value_report/i18n/stock_move_value_report.pot
  stock_move_value_report/readme/CONTRIBUTORS.rst
  stock_move_value_report/readme/DESCRIPTION.rst
  stock_move_value_report/readme/USAGE.rst
  stock_move_value_report/report/stock_inventory_value_report.xml
  stock_move_value_report/report/stock_move_line_value_report.xml
  stock_move_value_report/report/stock_move_value_report.xml
  stock_move_value_report/report/stock_picking_value_report.xml
  stock_move_value_report/report/stock_scrap_value_report.xml
  stock_move_value_report/report/stock_value_report.xml
  stock_move_value_report/static/description/icon.png
  stock_move_value_report/static/description/index.html
Labels: approved, bot is merging ⏳, migration

#120 [13.0][FIX] stock_picking_report_valued: Make visible valued_picking field in customer
  stock_picking_report_valued/views/res_partner_view.xml
Labels: bot is merging ⏳

#114 [12.0][ADD] stock_picking_report_undelivered_product: New module to display undelivered products in delivery slip report
  stock_picking_report_undelivered_product/README.rst
  stock_picking_report_undelivered_product/__init__.py
  stock_picking_report_undelivered_product/__manifest__.py
  stock_picking_report_undelivered_product/i18n/es.po
  stock_picking_report_undelivered_product/i18n/stock_picking_report_undelivered_product.pot
  stock_picking_report_undelivered_product/models/__init__.py
  stock_picking_report_undelivered_product/models/product_template.py
  stock_picking_report_undelivered_product/models/res_config_settings.py
  stock_picking_report_undelivered_product/models/res_partner.py
  stock_picking_report_undelivered_product/models/stock_move.py
  stock_picking_report_undelivered_product/readme/CONTRIBUTORS.rst
  stock_picking_report_undelivered_product/readme/DESCRIPTION.rst
  stock_picking_report_undelivered_product/readme/USAGE.rst
  stock_picking_report_undelivered_product/static/description/index.html
  stock_picking_report_undelivered_product/tests/__init__.py
  stock_picking_report_undelivered_product/tests/test_stock_picking_report_undelivered_product.py
  stock_picking_report_undelivered_product/views/product_views.xml
  stock_picking_report_undelivered_product/views/report_deliveryslip.xml
  stock_picking_report_undelivered_product/views/res_config_settings_views.xml
  stock_picking_report_undelivered_product/views/res_partner_view.xml
Labels: approved, bot is merging ⏳, needs review
