Repository OCA/stock-logistics-reporting, pull requests merged in 2021-11, with the labels that each got.

#172 [FIX] stock_picking_report_valued_sale_mrp: multipicking
  stock_picking_report_valued_sale_mrp/models/stock_move_line.py
Labels: bot is merging ⏳

#156 [14.0][MIG] stock_quantity_history_location
  setup/stock_quantity_history_location/odoo/addons/stock_quantity_history_location
  setup/stock_quantity_history_location/setup.py
  stock_quantity_history_location/README.rst
  stock_quantity_history_location/__init__.py
  stock_quantity_history_location/__manifest__.py
  stock_quantity_history_location/i18n/it.po
  stock_quantity_history_location/i18n/ro.po
  stock_quantity_history_location/i18n/stock_quantity_history_location.pot
  stock_quantity_history_location/readme/CONSTRIBUTORS.rst
  stock_quantity_history_location/readme/DESCRIPTION.rst
  stock_quantity_history_location/readme/USAGE.rst
  stock_quantity_history_location/static/description/icon.png
  stock_quantity_history_location/static/description/index.html
  stock_quantity_history_location/static/src/js/inventory_report.js
  stock_quantity_history_location/tests/__init__.py
  stock_quantity_history_location/tests/common.py
  stock_quantity_history_location/tests/test_stock_quantity_history_location.py
  stock_quantity_history_location/wizards/__init__.py
  stock_quantity_history_location/wizards/stock_quantity_history.py
  stock_quantity_history_location/wizards/stock_quantity_history.xml
Labels: approved, bot is merging ⏳

#130 [12.0][FIX] stock_picking_report_valued: Round computed price to avoid difference
  stock_picking_report_valued/models/stock_move_line.py
  stock_picking_report_valued/tests/test_stock_picking_valued.py
Labels: approved, bot is merging ⏳

#150 [stock_report_quantity_by_location][imp] allow to report based on availability.
  stock_report_quantity_by_location/wizards/stock_report_quantity_by_location.py
  stock_report_quantity_by_location/wizards/stock_report_quantity_by_location_views.xml
Labels: approved, bot is merging ⏳

#153 [14.0] mig stock_picking_comment_template
  oca_dependencies.txt
  stock_picking_comment_template/README.rst
  stock_picking_comment_template/__init__.py
  stock_picking_comment_template/__manifest__.py
  stock_picking_comment_template/i18n/de.po
  stock_picking_comment_template/i18n/ja.po
  stock_picking_comment_template/i18n/stock_picking_comment_template.pot
  stock_picking_comment_template/models/__init__.py
  stock_picking_comment_template/models/stock_picking.py
  stock_picking_comment_template/readme/CONTRIBUTORS.rst
  stock_picking_comment_template/readme/DESCRIPTION.rst
  stock_picking_comment_template/security/ir.model.access.csv
  stock_picking_comment_template/static/description/icon.png
  stock_picking_comment_template/static/description/index.html
  stock_picking_comment_template/tests/__init__.py
  stock_picking_comment_template/tests/test_stock_picking_report.py
  stock_picking_comment_template/views/base_comment_template_view.xml
  stock_picking_comment_template/views/report_delivery_document.xml
  stock_picking_comment_template/views/report_picking.xml
  stock_picking_comment_template/views/stock_picking_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#171 [15.0][MIG]stock_account_valuation_report
  setup/stock_account_valuation_report/odoo/addons/stock_account_valuation_report
  setup/stock_account_valuation_report/setup.py
  stock_account_valuation_report/README.rst
  stock_account_valuation_report/__init__.py
  stock_account_valuation_report/__manifest__.py
  stock_account_valuation_report/i18n/es.po
  stock_account_valuation_report/i18n/es_MX.po
  stock_account_valuation_report/i18n/fr.po
  stock_account_valuation_report/i18n/sl.po
  stock_account_valuation_report/i18n/stock_account_valuation_report.pot
  stock_account_valuation_report/models/__init__.py
  stock_account_valuation_report/models/account_move_line.py
  stock_account_valuation_report/models/product_product.py
  stock_account_valuation_report/readme/CONTRIBUTORS.rst
  stock_account_valuation_report/readme/DESCRIPTION.rst
  stock_account_valuation_report/security/ir.model.access.csv
  stock_account_valuation_report/static/description/icon.png
  stock_account_valuation_report/static/description/index.html
  stock_account_valuation_report/tests/__init__.py
  stock_account_valuation_report/tests/test_stock_account_valuation_report.py
  stock_account_valuation_report/views/product_product_views.xml
  stock_account_valuation_report/wizards/__init__.py
  stock_account_valuation_report/wizards/stock_valuation_history.py
  stock_account_valuation_report/wizards/stock_valuation_history.xml
Labels: needs review, approved, migration, bot is merging ⏳

#157 [14.0][MIG] stock_account_quantity_history_location
  setup/stock_account_quantity_history_location/odoo/addons/stock_account_quantity_history_location
  setup/stock_account_quantity_history_location/setup.py
  stock_account_quantity_history_location/README.rst
  stock_account_quantity_history_location/__init__.py
  stock_account_quantity_history_location/__manifest__.py
  stock_account_quantity_history_location/i18n/fr.po
  stock_account_quantity_history_location/i18n/stock_account_quantity_history_location.pot
  stock_account_quantity_history_location/readme/CONSTRIBUTORS.rst
  stock_account_quantity_history_location/readme/DESCRIPTION.rst
  stock_account_quantity_history_location/static/description/icon.png
  stock_account_quantity_history_location/static/description/index.html
  stock_account_quantity_history_location/tests/__init__.py
  stock_account_quantity_history_location/tests/test_valuation_location.py
  stock_account_quantity_history_location/wizards/__init__.py
  stock_account_quantity_history_location/wizards/stock_quantity_history.py
  stock_account_quantity_history_location/wizards/stock_quantity_history.xml
Labels: bot is merging ⏳
