Repository OCA/stock-logistics-reporting, pull requests merged in 2021-04, with the labels that each got.

#124 [14.0][MIG] stock_card_report
  setup/stock_card_report/odoo/addons/stock_card_report
  setup/stock_card_report/setup.py
  stock_card_report/README.rst
  stock_card_report/__init__.py
  stock_card_report/__manifest__.py
  stock_card_report/data/paper_format.xml
  stock_card_report/data/report_data.xml
  stock_card_report/i18n/es.po
  stock_card_report/i18n/es_EC.po
  stock_card_report/i18n/stock_card_report.pot
  stock_card_report/readme/CONTRIBUTORS.rst
  stock_card_report/readme/DESCRIPTION.rst
  stock_card_report/readme/USAGE.rst
  stock_card_report/reports/__init__.py
  stock_card_report/reports/stock_card_report.py
  stock_card_report/reports/stock_card_report.xml
  stock_card_report/reports/stock_card_report_xlsx.py
  stock_card_report/security/ir.model.access.csv
  stock_card_report/static/description/icon.png
  stock_card_report/static/description/index.html
  stock_card_report/static/src/css/report.css
  stock_card_report/static/src/js/stock_card_report_backend.js
  stock_card_report/tests/__init__.py
  stock_card_report/tests/test_stock_card_report.py
  stock_card_report/wizard/__init__.py
  stock_card_report/wizard/stock_card_report_wizard.py
  stock_card_report/wizard/stock_card_report_wizard_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#134 [13.0][MIG] stock_picking_report_undelivered_product: Module migration
  setup/stock_picking_report_undelivered_product/odoo/addons/stock_picking_report_undelivered_product
  setup/stock_picking_report_undelivered_product/setup.py
  stock_picking_report_undelivered_product/README.rst
  stock_picking_report_undelivered_product/__init__.py
  stock_picking_report_undelivered_product/__manifest__.py
  stock_picking_report_undelivered_product/i18n/es.po
  stock_picking_report_undelivered_product/i18n/stock_picking_report_undelivered_product.pot
  stock_picking_report_undelivered_product/models/__init__.py
  stock_picking_report_undelivered_product/models/product_template.py
  stock_picking_report_undelivered_product/models/res_config_settings.py
  stock_picking_report_undelivered_product/models/res_partner.py
  stock_picking_report_undelivered_product/models/stock_move.py
  stock_picking_report_undelivered_product/readme/CONTRIBUTORS.rst
  stock_picking_report_undelivered_product/readme/DESCRIPTION.rst
  stock_picking_report_undelivered_product/readme/USAGE.rst
  stock_picking_report_undelivered_product/static/description/icon.png
  stock_picking_report_undelivered_product/static/description/index.html
  stock_picking_report_undelivered_product/tests/__init__.py
  stock_picking_report_undelivered_product/tests/test_stock_picking_report_undelivered_product.py
  stock_picking_report_undelivered_product/views/product_views.xml
  stock_picking_report_undelivered_product/views/report_deliveryslip.xml
  stock_picking_report_undelivered_product/views/res_config_settings_views.xml
  stock_picking_report_undelivered_product/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#145 [14.0][FIX] stock_card_report, fix action access error
  stock_card_report/wizard/stock_card_report_wizard.py
Labels: bot is merging ⏳

#141 [14.0][IMP] stock_card_report, add origin to display_name on report
  stock_card_report/reports/stock_card_report.py
  stock_card_report/reports/stock_card_report.xml
  stock_card_report/reports/stock_card_report_xlsx.py
Labels: approved, bot is merging ⏳
