Repository OCA/stock-logistics-reporting, pull requests merged in 2021-05, with the labels that each got.

#144 [13.0][mig] stock_report_quantity_by_location
  setup/stock_report_quantity_by_location/odoo/addons/stock_report_quantity_by_location
  setup/stock_report_quantity_by_location/setup.py
  stock_report_quantity_by_location/__init__.py
  stock_report_quantity_by_location/__manifest__.py
  stock_report_quantity_by_location/i18n/es_MX.po
  stock_report_quantity_by_location/i18n/stock_report_quantity_by_location.pot
  stock_report_quantity_by_location/readme/CONTRIBUTORS.rst
  stock_report_quantity_by_location/readme/DESCRIPTION.rst
  stock_report_quantity_by_location/static/description/icon.png
  stock_report_quantity_by_location/static/description/index.html
  stock_report_quantity_by_location/tests/__init__.py
  stock_report_quantity_by_location/tests/test_stock_report_quantity_by_location.py
  stock_report_quantity_by_location/wizards/__init__.py
  stock_report_quantity_by_location/wizards/stock_report_quantity_by_location.py
  stock_report_quantity_by_location/wizards/stock_report_quantity_by_location_views.xml
Labels: approved, bot is merging ⏳

#147 [FIX] stock_move_value_report: fix remanent BS3 classes
  stock_move_value_report/report/stock_move_line_value_report.xml
  stock_move_value_report/report/stock_picking_value_report.xml
Labels: approved, bot is merging ⏳

#142 [FIX] stock_picking_report_valued_sale_mrp: ignored cancelled order
  stock_picking_report_valued_sale_mrp/models/stock_move.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#140 [12.0][FIX] stock_inventory_valuation_report: show quantity in the past for currently not available products
  stock_inventory_valuation_report/__manifest__.py
  stock_inventory_valuation_report/reports/stock_inventory_valuation_report.py
  stock_inventory_valuation_report/tests/test_stock_inventory_valuation_report.py
Labels: approved, bot is merging ⏳, ready to merge

#148 [13.0][IMP] stock_quantity_history_location: Add functions in test to allow re-use by othher addons
  stock_quantity_history_location/tests/common.py
  stock_quantity_history_location/tests/test_stock_quantity_history_location.py
  stock_quantity_history_location/wizards/stock_quantity_history.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#146 [13.0][MIG] stock_account_quantity_history_location: Migration to 13.0
  setup/stock_account_quantity_history_location/odoo/addons/stock_account_quantity_history_location
  setup/stock_account_quantity_history_location/setup.py
  stock_account_quantity_history_location/README.rst
  stock_account_quantity_history_location/__init__.py
  stock_account_quantity_history_location/__manifest__.py
  stock_account_quantity_history_location/i18n/fr.po
  stock_account_quantity_history_location/i18n/stock_account_quantity_history_location.pot
  stock_account_quantity_history_location/readme/CONSTRIBUTORS.rst
  stock_account_quantity_history_location/readme/DESCRIPTION.rst
  stock_account_quantity_history_location/static/description/icon.png
  stock_account_quantity_history_location/static/description/index.html
  stock_account_quantity_history_location/tests/__init__.py
  stock_account_quantity_history_location/tests/test_valuation_location.py
  stock_account_quantity_history_location/wizards/__init__.py
  stock_account_quantity_history_location/wizards/stock_quantity_history.py
  stock_account_quantity_history_location/wizards/stock_quantity_history.xml
Labels: approved, bot is merging ⏳, migration, needs review
