Repository OCA/stock-logistics-reporting, pull requests merged in 2021-03, with the labels that each got.

#110 [11.0] [FIX] stock_picking_comment_template Contributors web
  stock_picking_comment_template/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#111 [12.0] [FIX] stock_picking_comment_template Contributors web
  stock_picking_comment_template/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#137 [ADD] stock_forecast_report: Backport from 14.0
  stock_forecast_report/README.rst
  stock_forecast_report/__init__.py
  stock_forecast_report/__manifest__.py
  stock_forecast_report/readme/CONTRIBUTORS.rst
  stock_forecast_report/readme/DESCRIPTION.rst
  stock_forecast_report/readme/ROADMAP.rst
  stock_forecast_report/readme/USAGE.rst
  stock_forecast_report/reports/__init__.py
  stock_forecast_report/reports/report_stock_quantity.py
  stock_forecast_report/reports/report_stock_quantity.xml
  stock_forecast_report/security/ir.model.access.csv
  stock_forecast_report/static/description/icon.png
  stock_forecast_report/static/description/index.html
  stock_forecast_report/static/description/screenshot_stock_forecast.png
  stock_forecast_report/tests/__init__.py
  stock_forecast_report/tests/test_report_stock_quantity.py
Labels: approved, bot is merging ⏳, ready to merge
