Repository OCA/stock-logistics-reporting, pull requests merged in 2022-03, with the labels that each got.

#182 [14.0][FIX] spgbpbcslp: Fix deliveryslip report lines order
  stock_picking_group_by_partner_by_carrier_sale_line_position/__init__.py
Labels: approved, bot is merging ⏳

#180 [13.0] [MIG] stock_move_value_report: Migration to 13.0
  setup/stock_move_value_report/odoo/addons/stock_move_value_report
  setup/stock_move_value_report/setup.py
  stock_move_value_report/README.rst
  stock_move_value_report/__init__.py
  stock_move_value_report/__manifest__.py
  stock_move_value_report/i18n/es.po
  stock_move_value_report/i18n/fr.po
  stock_move_value_report/i18n/pt.po
  stock_move_value_report/i18n/stock_move_value_report.pot
  stock_move_value_report/readme/CONTRIBUTORS.rst
  stock_move_value_report/readme/DESCRIPTION.rst
  stock_move_value_report/readme/USAGE.rst
  stock_move_value_report/report/stock_inventory_value_report.xml
  stock_move_value_report/report/stock_move_line_value_report.xml
  stock_move_value_report/report/stock_move_value_report.xml
  stock_move_value_report/report/stock_picking_value_report.xml
  stock_move_value_report/report/stock_scrap_value_report.xml
  stock_move_value_report/report/stock_value_report.xml
  stock_move_value_report/static/description/icon.png
  stock_move_value_report/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#166 [13.0][IMP]stock-quantity-history-location: Enable selecting a view location in wizard
  stock_quantity_history_location/wizards/stock_quantity_history.py
Labels: bot is merging ⏳, stale

#163 [13.0][ADD] stock_inventory_valuation_unit_cost
  setup/stock_inventory_valuation_unit_cost/odoo/addons/stock_inventory_valuation_unit_cost
  setup/stock_inventory_valuation_unit_cost/setup.py
  stock_inventory_valuation_unit_cost/README.rst
  stock_inventory_valuation_unit_cost/__init__.py
  stock_inventory_valuation_unit_cost/__manifest__.py
  stock_inventory_valuation_unit_cost/readme/CONTRIBUTORS.rst
  stock_inventory_valuation_unit_cost/readme/DESCRIPTION.rst
  stock_inventory_valuation_unit_cost/static/description/icon.png
  stock_inventory_valuation_unit_cost/static/description/index.html
  stock_inventory_valuation_unit_cost/views/stock_valuation_layer_views.xml
Labels: bot is merging ⏳, stale

#122 [12.0][FIX] stock_card_report: display the correct product name
  stock_card_report/reports/stock_card_report.xml
Labels: bot is merging ⏳, stale

#187 Updated from template - Switch to Github actions
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .travis.yml
  README.md
  stock_picking_report_valued/tests/test_stock_picking_valued.py
Labels: enhancement
