Repository OCA/stock-logistics-reporting, pull requests merged in 2022-08, with the labels that each got.

#209 [14.0][MIG] stock_picking_report_custom_description: Migration to version 14.0
  setup/stock_picking_report_custom_description/odoo/addons/stock_picking_report_custom_description
  setup/stock_picking_report_custom_description/setup.py
  stock_picking_report_custom_description/README.rst
  stock_picking_report_custom_description/__init__.py
  stock_picking_report_custom_description/__manifest__.py
  stock_picking_report_custom_description/i18n/es.po
  stock_picking_report_custom_description/i18n/stock_picking_report_custom_description.pot
  stock_picking_report_custom_description/readme/CONTRIBUTORS.rst
  stock_picking_report_custom_description/readme/DESCRIPTION.rst
  stock_picking_report_custom_description/readme/USAGE.rst
  stock_picking_report_custom_description/static/description/icon.png
  stock_picking_report_custom_description/static/description/index.html
  stock_picking_report_custom_description/views/report_deliveryslip.xml
  stock_picking_report_custom_description/views/report_stockpicking_operations.xml
  stock_picking_report_custom_description/views/stock_report.xml
Labels: approved, ready to merge, bot is merging ⏳

#181 [15.0][MIG] stock_picking_report_valued
  setup/stock_picking_report_valued/odoo/addons/stock_picking_report_valued
  setup/stock_picking_report_valued/setup.py
  stock_picking_report_valued/README.rst
  stock_picking_report_valued/__init__.py
  stock_picking_report_valued/__manifest__.py
  stock_picking_report_valued/i18n/es.po
  stock_picking_report_valued/i18n/fr_FR.po
  stock_picking_report_valued/i18n/hr.po
  stock_picking_report_valued/i18n/ro.po
  stock_picking_report_valued/i18n/stock_picking_report_valued.pot
  stock_picking_report_valued/models/__init__.py
  stock_picking_report_valued/models/res_partner.py
  stock_picking_report_valued/models/stock_move_line.py
  stock_picking_report_valued/models/stock_picking.py
  stock_picking_report_valued/readme/CONFIGURE.rst
  stock_picking_report_valued/readme/CONTRIBUTORS.rst
  stock_picking_report_valued/readme/DESCRIPTION.rst
  stock_picking_report_valued/readme/ROADMAP.rst
  stock_picking_report_valued/readme/USAGE.rst
  stock_picking_report_valued/report/stock_picking_report_valued.xml
  stock_picking_report_valued/static/description/icon.png
  stock_picking_report_valued/static/description/index.html
  stock_picking_report_valued/tests/__init__.py
  stock_picking_report_valued/tests/test_stock_picking_valued.py
  stock_picking_report_valued/views/res_partner_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#213 [14.0][MIG] stock_inventory_valuation_pivot
  setup/stock_inventory_valuation_pivot/odoo/addons/stock_inventory_valuation_pivot
  setup/stock_inventory_valuation_pivot/setup.py
  stock_inventory_valuation_pivot/README.rst
  stock_inventory_valuation_pivot/__init__.py
  stock_inventory_valuation_pivot/__manifest__.py
  stock_inventory_valuation_pivot/i18n/es.po
  stock_inventory_valuation_pivot/i18n/stock_inventory_valuation_pivot.pot
  stock_inventory_valuation_pivot/readme/CONTRIBUTORS.rst
  stock_inventory_valuation_pivot/readme/DESCRIPTION.rst
  stock_inventory_valuation_pivot/readme/USAGE.rst
  stock_inventory_valuation_pivot/static/description/icon.png
  stock_inventory_valuation_pivot/static/description/index.html
  stock_inventory_valuation_pivot/views/stock_account_views.xml
Labels: approved, bot is merging ⏳

#212 [13.0][FIX] stock_account_quantity_history_location: Remove domains.
  stock_account_quantity_history_location/wizards/stock_quantity_history.py
Labels: bot is merging ⏳

#214 [14.0][FIX] stock_account_quantity_history_location: 2 fw-ports
  stock_account_quantity_history_location/wizards/stock_quantity_history.py
Labels: bot is merging ⏳

#215 [14.0][IMP] stock_inventory_valuation_pivot: transform field to filter in search view
  stock_inventory_valuation_pivot/views/stock_account_views.xml
Labels: bot is merging ⏳
