Repository OCA/stock-logistics-reporting, pull requests merged in 2022-10, with the labels that each got.

#197 14.0 stock_picking_report_valued
  stock_picking_report_valued/models/stock_move_line.py
  stock_picking_report_valued/readme/ROADMAP.rst
  stock_picking_report_valued/report/stock_picking_report_valued.xml
Labels: approved, bot is merging ⏳

#207 [15.0][FIX] stock_account_valuation_report: exclude JE that are not posted
  stock_account_valuation_report/models/product_product.py
Labels: approved, ready to merge, bot is merging ⏳

#231 Revert "14.0 stock_picking_report_valued"
  stock_picking_report_valued/models/stock_move_line.py
  stock_picking_report_valued/readme/ROADMAP.rst
  stock_picking_report_valued/report/stock_picking_report_valued.xml
Labels: needs review, bot is merging ⏳

#178 [12.0][ADD] Report picking summary
  stock_picking_report_summary/README.rst
  stock_picking_report_summary/__init__.py
  stock_picking_report_summary/__manifest__.py
  stock_picking_report_summary/i18n/fr.po
  stock_picking_report_summary/models/__init__.py
  stock_picking_report_summary/models/picking_summary_wizard.py
  stock_picking_report_summary/models/picking_summary_wizard_picking.py
  stock_picking_report_summary/models/picking_summary_wizard_product.py
  stock_picking_report_summary/readme/CONTRIBUTORS.rst
  stock_picking_report_summary/readme/DESCRIPTION.rst
  stock_picking_report_summary/readme/USAGE.rst
  stock_picking_report_summary/reports/report_paperformat.xml
  stock_picking_report_summary/reports/report_print_picking_summary.xml
  stock_picking_report_summary/reports/report_print_picking_summary_template.xml
  stock_picking_report_summary/static/description/icon.png
  stock_picking_report_summary/static/description/index.html
  stock_picking_report_summary/static/description/pdf_report.png
  stock_picking_report_summary/static/description/pdf_report_wo_prices.png
  stock_picking_report_summary/static/description/wizard.png
  stock_picking_report_summary/views/action.xml
  stock_picking_report_summary/views/view_picking_summary_wizard.xml
Labels: needs review, approved, bot is merging ⏳

#170 [14.0][MIG]stock_account_valuation_report
  setup/stock_account_valuation_report/odoo/addons/stock_account_valuation_report
  setup/stock_account_valuation_report/setup.py
  stock_account_valuation_report/README.rst
  stock_account_valuation_report/__init__.py
  stock_account_valuation_report/__manifest__.py
  stock_account_valuation_report/i18n/es.po
  stock_account_valuation_report/i18n/es_MX.po
  stock_account_valuation_report/i18n/fr.po
  stock_account_valuation_report/i18n/sl.po
  stock_account_valuation_report/i18n/stock_account_valuation_report.pot
  stock_account_valuation_report/models/__init__.py
  stock_account_valuation_report/models/account_move_line.py
  stock_account_valuation_report/models/product_product.py
  stock_account_valuation_report/readme/CONTRIBUTORS.rst
  stock_account_valuation_report/readme/DESCRIPTION.rst
  stock_account_valuation_report/security/ir.model.access.csv
  stock_account_valuation_report/static/description/icon.png
  stock_account_valuation_report/static/description/index.html
  stock_account_valuation_report/tests/__init__.py
  stock_account_valuation_report/tests/test_stock_account_valuation_report.py
  stock_account_valuation_report/views/product_product_views.xml
  stock_account_valuation_report/wizards/__init__.py
  stock_account_valuation_report/wizards/stock_valuation_history.py
  stock_account_valuation_report/wizards/stock_valuation_history.xml
Labels: needs review, migration, bot is merging ⏳

#186 [15.0][MIG] stock_card_report
  setup/stock_card_report/odoo/addons/stock_card_report
  setup/stock_card_report/setup.py
  stock_card_report/README.rst
  stock_card_report/__init__.py
  stock_card_report/__manifest__.py
  stock_card_report/data/paper_format.xml
  stock_card_report/data/report_data.xml
  stock_card_report/i18n/es.po
  stock_card_report/i18n/es_EC.po
  stock_card_report/i18n/stock_card_report.pot
  stock_card_report/readme/CONTRIBUTORS.rst
  stock_card_report/readme/DESCRIPTION.rst
  stock_card_report/readme/USAGE.rst
  stock_card_report/reports/__init__.py
  stock_card_report/reports/stock_card_report.py
  stock_card_report/reports/stock_card_report.xml
  stock_card_report/reports/stock_card_report_xlsx.py
  stock_card_report/security/ir.model.access.csv
  stock_card_report/static/description/icon.png
  stock_card_report/static/description/index.html
  stock_card_report/static/src/css/report.css
  stock_card_report/static/src/js/stock_card_report_backend.esm.js
  stock_card_report/tests/__init__.py
  stock_card_report/tests/test_stock_card_report.py
  stock_card_report/wizard/__init__.py
  stock_card_report/wizard/stock_card_report_wizard.py
  stock_card_report/wizard/stock_card_report_wizard_view.xml
Labels: needs review, approved, migration, bot is merging ⏳, stale

#233 [14.0][FIX] stock_picking_report_valued: Remove WARNING log error.
  stock_picking_report_valued/models/stock_move_line.py
Labels: bot is merging ⏳

#236 [FIX] stock_picking_report_valued: Fix display columns when display lots in delivery slip
  stock_picking_report_valued/report/stock_picking_report_valued.xml
Labels: approved, bot is merging ⏳

#235 [12.0][FIX] stock_inventory_turnover_report: Fix of the date miscalculation
  stock_inventory_turnover_report/models/product_product.py
Labels: bot is merging ⏳

#177 [14.0] [IMP] Allow dynamic base comment template rendering.
  stock_picking_comment_template/views/report_delivery_document.xml
  stock_picking_comment_template/views/report_picking.xml
Labels: enhancement, needs review, bot is merging ⏳

#239 [14.0][IMP] stock_picking_report_valued: Update ROADMAP.rst
  stock_picking_report_valued/readme/ROADMAP.rst
Labels: approved, bot is merging ⏳

#237 [13.0][FIX] stock_picking_report_valued: Access error due to inconsistent 'computo_sudo'
  stock_picking_report_valued/models/stock_move_line.py
Labels: approved, bot is merging ⏳
