Repository OCA/stock-logistics-reporting, pull requests merged in 2022-09, with the labels that each got.

#217 [15.0][FIX] stock_picking_report_valued: Calculate price unit correctly con…
  stock_picking_report_valued/models/stock_move_line.py
Labels: approved, bot is merging ⏳

#218 [14.0][FIX] stock_picking_report_valued: Calculate price unit correctly con…
  stock_picking_report_valued/models/stock_move_line.py
Labels: bot is merging ⏳

#203 [15.0] [MIG] stock_report_quantity_by_location
  setup/stock_report_quantity_by_location/odoo/addons/stock_report_quantity_by_location
  setup/stock_report_quantity_by_location/setup.py
  stock_report_quantity_by_location/README.rst
  stock_report_quantity_by_location/__init__.py
  stock_report_quantity_by_location/__manifest__.py
  stock_report_quantity_by_location/i18n/es_MX.po
  stock_report_quantity_by_location/i18n/stock_report_quantity_by_location.pot
  stock_report_quantity_by_location/readme/CONTRIBUTORS.rst
  stock_report_quantity_by_location/readme/DESCRIPTION.rst
  stock_report_quantity_by_location/security/ir.model.access.csv
  stock_report_quantity_by_location/static/description/icon.png
  stock_report_quantity_by_location/static/description/index.html
  stock_report_quantity_by_location/tests/__init__.py
  stock_report_quantity_by_location/tests/test_stock_report_quantity_by_location.py
  stock_report_quantity_by_location/wizards/__init__.py
  stock_report_quantity_by_location/wizards/stock_report_quantity_by_location.py
  stock_report_quantity_by_location/wizards/stock_report_quantity_by_location_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#219 [13.0][FIX] stock_picking_report_valued: Calculate price unit correctly con…
  stock_picking_report_valued/models/stock_move_line.py
Labels: bot is merging ⏳

#221 [13.0][FIX] stock_picking_report_valued: valued line computation
  stock_picking_report_valued/models/stock_move_line.py
Labels: approved, bot is merging ⏳

#223 [FIX][14.0] delete unwanted file
  log --graph --pretty=format:%Cred%h%Creset\ -%C(yellow)%d%Creset\ %s\ %Cgreen(%cr)\ %C(bold\ blue)<%an>%Creset --abbrev-commit -p
Labels: bot is merging ⏳

#224 [15.0][FW] stock_picking_report_valued: rounding issues
  stock_picking_report_valued/__manifest__.py
  stock_picking_report_valued/models/stock_move_line.py
  stock_picking_report_valued/models/stock_picking.py
  stock_picking_report_valued/tests/test_stock_picking_valued.py
Labels: bot is merging ⏳

#226 [FIX] Always show qty_done on picking report:
  stock_picking_report_valued/report/stock_picking_report_valued.xml
Labels: approved, bot is merging ⏳

#173 [14.0][MIG] stock_report_quantity_by_location: migration from 13.0 to 14.0
  setup/stock_report_quantity_by_location/odoo/addons/stock_report_quantity_by_location
  setup/stock_report_quantity_by_location/setup.py
  stock_report_quantity_by_location/README.rst
  stock_report_quantity_by_location/__init__.py
  stock_report_quantity_by_location/__manifest__.py
  stock_report_quantity_by_location/i18n/es_MX.po
  stock_report_quantity_by_location/i18n/stock_report_quantity_by_location.pot
  stock_report_quantity_by_location/readme/CONTRIBUTORS.rst
  stock_report_quantity_by_location/readme/DESCRIPTION.rst
  stock_report_quantity_by_location/security/ir.model.access.csv
  stock_report_quantity_by_location/static/description/icon.png
  stock_report_quantity_by_location/static/description/index.html
  stock_report_quantity_by_location/tests/__init__.py
  stock_report_quantity_by_location/tests/test_stock_report_quantity_by_location.py
  stock_report_quantity_by_location/wizards/__init__.py
  stock_report_quantity_by_location/wizards/stock_report_quantity_by_location.py
  stock_report_quantity_by_location/wizards/stock_report_quantity_by_location_views.xml
Labels: bot is merging ⏳
