Repository OCA/stock-logistics-reporting, pull requests merged in 2023-03, with the labels that each got.

#266 [15.0][MIG] stock_picking_report_valued_sale_mrp: Migration to version 15.0
  setup/stock_picking_report_valued_sale_mrp/odoo/addons/stock_picking_report_valued_sale_mrp
  setup/stock_picking_report_valued_sale_mrp/setup.py
  stock_card_report/static/src/js/stock_card_report_backend.esm.js
  stock_picking_report_valued_sale_mrp/README.rst
  stock_picking_report_valued_sale_mrp/__init__.py
  stock_picking_report_valued_sale_mrp/__manifest__.py
  stock_picking_report_valued_sale_mrp/i18n/stock_picking_report_valued_sale_mrp.pot
  stock_picking_report_valued_sale_mrp/models/__init__.py
  stock_picking_report_valued_sale_mrp/models/stock_move.py
  stock_picking_report_valued_sale_mrp/models/stock_move_line.py
  stock_picking_report_valued_sale_mrp/readme/CONTRIBUTORS.rst
  stock_picking_report_valued_sale_mrp/readme/DESCRIPTION.rst
  stock_picking_report_valued_sale_mrp/readme/ROADMAP.rst
  stock_picking_report_valued_sale_mrp/readme/USAGE.rst
  stock_picking_report_valued_sale_mrp/report/stock_picking_report_valued.xml
  stock_picking_report_valued_sale_mrp/static/description/icon.png
  stock_picking_report_valued_sale_mrp/static/description/index.html
  stock_picking_report_valued_sale_mrp/tests/__init__.py
  stock_picking_report_valued_sale_mrp/tests/test_stock_picking_report_valued_mrp.py
Labels: approved, bot is merging ⏳

#263 [ADD] [15.0] stock_picking_report_product_sticker
  setup/stock_picking_report_product_sticker/odoo/addons/stock_picking_report_product_sticker
  setup/stock_picking_report_product_sticker/setup.py
  stock_picking_report_product_sticker/README.rst
  stock_picking_report_product_sticker/__init__.py
  stock_picking_report_product_sticker/__manifest__.py
  stock_picking_report_product_sticker/data/menus.xml
  stock_picking_report_product_sticker/models/__init__.py
  stock_picking_report_product_sticker/models/stock_picking.py
  stock_picking_report_product_sticker/models/stock_picking_type.py
  stock_picking_report_product_sticker/readme/CONTRIBUTORS.rst
  stock_picking_report_product_sticker/readme/DESCRIPTION.rst
  stock_picking_report_product_sticker/readme/INSTALL.rst
  stock_picking_report_product_sticker/readme/USAGE.rst
  stock_picking_report_product_sticker/report/report_deliveryslip.xml
  stock_picking_report_product_sticker/static/description/icon.png
  stock_picking_report_product_sticker/static/description/index.html
  stock_picking_report_product_sticker/tests/__init__.py
  stock_picking_report_product_sticker/tests/common.py
  stock_picking_report_product_sticker/tests/test_stock_picking.py
  stock_picking_report_product_sticker/views/stock_picking_type_views.xml
  stock_picking_report_product_sticker/views/stock_picking_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#269 [15.0][ADD] stock_picking_report_external_note
  setup/stock_picking_report_external_note/odoo/addons/stock_picking_report_external_note
  setup/stock_picking_report_external_note/setup.py
  stock_picking_report_external_note/README.rst
  stock_picking_report_external_note/__init__.py
  stock_picking_report_external_note/__manifest__.py
  stock_picking_report_external_note/i18n/es.po
  stock_picking_report_external_note/i18n/stock_picking_report_external_note.pot
  stock_picking_report_external_note/models/__init__.py
  stock_picking_report_external_note/models/stock_picking.py
  stock_picking_report_external_note/readme/CONTRIBUTORS.rst
  stock_picking_report_external_note/readme/DESCRIPTION.rst
  stock_picking_report_external_note/readme/USAGE.rst
  stock_picking_report_external_note/report/report_deliveryslip.xml
  stock_picking_report_external_note/static/description/icon.png
  stock_picking_report_external_note/static/description/icon.svg
  stock_picking_report_external_note/views/stock_picking_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#272 [15.0][MIG] stock_quantity_history_location: Migration to version 15.0
  setup/stock_quantity_history_location/odoo/addons/stock_quantity_history_location
  setup/stock_quantity_history_location/setup.py
  stock_quantity_history_location/README.rst
  stock_quantity_history_location/__init__.py
  stock_quantity_history_location/__manifest__.py
  stock_quantity_history_location/i18n/it.po
  stock_quantity_history_location/i18n/ja.po
  stock_quantity_history_location/i18n/ro.po
  stock_quantity_history_location/i18n/stock_quantity_history_location.pot
  stock_quantity_history_location/readme/CONTRIBUTORS.rst
  stock_quantity_history_location/readme/DESCRIPTION.rst
  stock_quantity_history_location/readme/USAGE.rst
  stock_quantity_history_location/static/description/icon.png
  stock_quantity_history_location/static/description/index.html
  stock_quantity_history_location/static/src/js/inventory_report.js
  stock_quantity_history_location/static/src/xml/inventory_report.xml
  stock_quantity_history_location/tests/__init__.py
  stock_quantity_history_location/tests/common.py
  stock_quantity_history_location/tests/test_stock_quantity_history_location.py
  stock_quantity_history_location/wizards/__init__.py
  stock_quantity_history_location/wizards/stock_quantity_history.py
  stock_quantity_history_location/wizards/stock_quantity_history.xml
Labels: approved, bot is merging ⏳

#268 [15.0][MIG] stock_account_quantity_history_location: Migration to version 15.0
  setup/stock_account_quantity_history_location/odoo/addons/stock_account_quantity_history_location
  setup/stock_account_quantity_history_location/setup.py
  stock_account_quantity_history_location/README.rst
  stock_account_quantity_history_location/__init__.py
  stock_account_quantity_history_location/__manifest__.py
  stock_account_quantity_history_location/i18n/fr.po
  stock_account_quantity_history_location/i18n/stock_account_quantity_history_location.pot
  stock_account_quantity_history_location/readme/CONTRIBUTORS.rst
  stock_account_quantity_history_location/readme/DESCRIPTION.rst
  stock_account_quantity_history_location/static/description/icon.png
  stock_account_quantity_history_location/static/description/index.html
  stock_account_quantity_history_location/tests/__init__.py
  stock_account_quantity_history_location/tests/test_valuation_location.py
  stock_account_quantity_history_location/wizards/__init__.py
  stock_account_quantity_history_location/wizards/stock_quantity_history.py
Labels: needs review, migration, bot is merging ⏳
