Repository OCA/stock-logistics-reporting, pull requests merged in 2023-02, with the labels that each got.

#262 [16.0] [UPD] copier
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: approved

#179 [13.0][FIX] stock_picking_report_valued_sale_mrp: multipicking
  stock_picking_report_valued_sale_mrp/models/stock_move_line.py
Labels: enhancement, needs review, bot is merging ⏳, stale

#261 [MIG] [16.0] `delivery_line_sale_line_position`: Migration to 16.0
  delivery_line_sale_line_position/README.rst
  delivery_line_sale_line_position/__init__.py
  delivery_line_sale_line_position/__manifest__.py
  delivery_line_sale_line_position/i18n/delivery_line_sale_line_position.pot
  delivery_line_sale_line_position/models/__init__.py
  delivery_line_sale_line_position/models/stock_move.py
  delivery_line_sale_line_position/models/stock_move_line.py
  delivery_line_sale_line_position/readme/CONTRIBUTORS.rst
  delivery_line_sale_line_position/readme/CREDITS.rst
  delivery_line_sale_line_position/readme/DESCRIPTION.rst
  delivery_line_sale_line_position/report/report_deliveryslip.xml
  delivery_line_sale_line_position/static/description/icon.png
  delivery_line_sale_line_position/static/description/index.html
  delivery_line_sale_line_position/views/stock_move.xml
  delivery_line_sale_line_position/views/stock_picking.xml
  setup/delivery_line_sale_line_position/odoo/addons/delivery_line_sale_line_position
  setup/delivery_line_sale_line_position/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#259 [16.0][MIG] stock_picking_report_valued: Migration to 16.0
  setup/stock_picking_report_valued/odoo/addons/stock_picking_report_valued
  setup/stock_picking_report_valued/setup.py
  stock_picking_report_valued/README.rst
  stock_picking_report_valued/__init__.py
  stock_picking_report_valued/__manifest__.py
  stock_picking_report_valued/i18n/es.po
  stock_picking_report_valued/i18n/fr_FR.po
  stock_picking_report_valued/i18n/hr.po
  stock_picking_report_valued/i18n/ro.po
  stock_picking_report_valued/i18n/stock_picking_report_valued.pot
  stock_picking_report_valued/models/__init__.py
  stock_picking_report_valued/models/res_partner.py
  stock_picking_report_valued/models/stock_move_line.py
  stock_picking_report_valued/models/stock_picking.py
  stock_picking_report_valued/readme/CONFIGURE.rst
  stock_picking_report_valued/readme/CONTRIBUTORS.rst
  stock_picking_report_valued/readme/DESCRIPTION.rst
  stock_picking_report_valued/readme/ROADMAP.rst
  stock_picking_report_valued/readme/USAGE.rst
  stock_picking_report_valued/report/stock_picking_report_valued.xml
  stock_picking_report_valued/static/description/icon.png
  stock_picking_report_valued/static/description/index.html
  stock_picking_report_valued/tests/__init__.py
  stock_picking_report_valued/tests/test_stock_picking_valued.py
  stock_picking_report_valued/views/res_partner_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
