Repository OCA/stock-logistics-reporting, pull requests merged in 2024-09, with the labels that each got.

#325 [16.0][MIG] stock_move_value_report: Migration to 16.0
  setup/stock_move_value_report/odoo/addons/stock_move_value_report
  setup/stock_move_value_report/setup.py
  stock_move_value_report/README.rst
  stock_move_value_report/__init__.py
  stock_move_value_report/__manifest__.py
  stock_move_value_report/i18n/es.po
  stock_move_value_report/i18n/fr.po
  stock_move_value_report/i18n/pt.po
  stock_move_value_report/i18n/stock_move_value_report.pot
  stock_move_value_report/readme/CONTRIBUTORS.rst
  stock_move_value_report/readme/DESCRIPTION.rst
  stock_move_value_report/readme/USAGE.rst
  stock_move_value_report/report/stock_inventory_value_report.xml
  stock_move_value_report/report/stock_move_line_value_report.xml
  stock_move_value_report/report/stock_move_value_report.xml
  stock_move_value_report/report/stock_picking_value_report.xml
  stock_move_value_report/report/stock_scrap_value_report.xml
  stock_move_value_report/report/stock_value_report.xml
  stock_move_value_report/static/description/icon.png
  stock_move_value_report/static/description/index.html
Labels: approved, migration, ready to merge, bot is merging ⏳

#307 [ADD] stock_quant_history_queued
  setup/stock_quant_history_queued/odoo/addons/stock_quant_history_queued
  setup/stock_quant_history_queued/setup.py
  stock_quant_history_queued/README.rst
  stock_quant_history_queued/__init__.py
  stock_quant_history_queued/__manifest__.py
  stock_quant_history_queued/i18n/fr.po
  stock_quant_history_queued/i18n/stock_quant_history_queued.pot
  stock_quant_history_queued/models/__init__.py
  stock_quant_history_queued/models/stock_quant_history_snapshot.py
  stock_quant_history_queued/readme/CONSTRIBUTORS.rst
  stock_quant_history_queued/readme/DESCRIPTION.rst
  stock_quant_history_queued/static/description/index.html
  stock_quant_history_queued/tests/__init__.py
  stock_quant_history_queued/tests/test_stock_quant_history_queued.py
Labels: approved, ready to merge, bot is merging ⏳

#336 [16.0][IMP] stock_average_daily_sale: support multi-warehouses
  stock_average_daily_sale/__manifest__.py
  stock_average_daily_sale/demo/stock_average_daily_sale_config.xml
  stock_average_daily_sale/migrations/16.0.1.1.0/pre-migrate.py
  stock_average_daily_sale/models/__init__.py
  stock_average_daily_sale/models/abc_classification_profile.py
  stock_average_daily_sale/models/stock_average_daily_sale.py
  stock_average_daily_sale/models/stock_average_daily_sale_config.py
  stock_average_daily_sale/models/stock_warehouse.py
  stock_average_daily_sale/security/stock_average_daily_sale.xml
  stock_average_daily_sale/security/stock_average_daily_sale_config.xml
  stock_average_daily_sale/tests/common.py
  stock_average_daily_sale/tests/test_average_daily_sale.py
  stock_average_daily_sale/views/abc_classification_profile.xml
  stock_average_daily_sale/views/stock_average_daily_sale_config.xml
  stock_average_daily_sale/views/stock_warehouse.xml
  stock_average_daily_sale/wizards/stock_average_daily_sale_demo.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#343 [16.0][FIX] stock_card_report: freeze datetime
  stock_card_report/tests/test_stock_card_report.py
Labels: bot is merging ⏳
