Repository OCA/stock-logistics-reporting, pull requests merged in 2024-07, with the labels that each got.

#331 [16.0][REF] stock_picking_report_delivery_driver: delete class attribute
  stock_picking_report_delivery_driver/report/report_stockpicking_operations.xml
Labels: bot is merging ⏳

#332 [16.0][FIX] stock_picking_report_salesperson: add the same class style as in the base report
  stock_picking_report_salesperson/report/report_deliveryslip.xml
Labels: bot is merging ⏳

#304 [16.0][MIG] stock_picking_report_summary
  setup/stock_picking_report_summary/odoo/addons/stock_picking_report_summary
  setup/stock_picking_report_summary/setup.py
  stock_picking_report_summary/README.rst
  stock_picking_report_summary/__init__.py
  stock_picking_report_summary/__manifest__.py
  stock_picking_report_summary/i18n/fr.po
  stock_picking_report_summary/readme/CONTRIBUTORS.rst
  stock_picking_report_summary/readme/DESCRIPTION.rst
  stock_picking_report_summary/readme/USAGE.rst
  stock_picking_report_summary/reports/report_print_picking_summary.xml
  stock_picking_report_summary/reports/report_print_picking_summary_template.xml
  stock_picking_report_summary/security/ir.model.access.csv
  stock_picking_report_summary/static/description/icon.png
  stock_picking_report_summary/static/description/index.html
  stock_picking_report_summary/static/description/new_print_action.png
  stock_picking_report_summary/static/description/pdf_report.png
  stock_picking_report_summary/static/description/wizard.png
  stock_picking_report_summary/tests/__init__.py
  stock_picking_report_summary/tests/test_module.py
  stock_picking_report_summary/wizards/__init__.py
  stock_picking_report_summary/wizards/picking_summary_wizard.py
  stock_picking_report_summary/wizards/picking_summary_wizard_picking.py
  stock_picking_report_summary/wizards/picking_summary_wizard_product.py
  stock_picking_report_summary/wizards/view_picking_summary_wizard.xml
Labels: needs review, approved, migration, bot is merging ⏳, stale

#294 [16.0][ADD] stock_picking_batch_report
  setup/stock_picking_batch_report/odoo/addons/stock_picking_batch_report
  setup/stock_picking_batch_report/setup.py
  stock_picking_batch_report/README.rst
  stock_picking_batch_report/__init__.py
  stock_picking_batch_report/__manifest__.py
  stock_picking_batch_report/models/__init__.py
  stock_picking_batch_report/models/stock_picking_batch.py
  stock_picking_batch_report/reports/report_picking_batch.xml
Labels: approved, bot is merging ⏳

#328 [16.0][ADD] stock_picking_operations_multilang
  setup/stock_picking_operations_multilang/odoo/addons/stock_picking_operations_multilang
  setup/stock_picking_operations_multilang/setup.py
  stock_picking_operations_multilang/README.rst
  stock_picking_operations_multilang/__init__.py
  stock_picking_operations_multilang/__manifest__.py
  stock_picking_operations_multilang/hooks.py
  stock_picking_operations_multilang/models/__init__.py
  stock_picking_operations_multilang/models/stock_picking.py
  stock_picking_operations_multilang/models/stock_warehouse.py
  stock_picking_operations_multilang/readme/CONFIGURE.rst
  stock_picking_operations_multilang/readme/CONTEXT.rst
  stock_picking_operations_multilang/readme/DESCRIPTION.rst
  stock_picking_operations_multilang/reports/picking_operations_report.xml
  stock_picking_operations_multilang/reports/report_picking_with_language.xml
  stock_picking_operations_multilang/static/description/index.html
  stock_picking_operations_multilang/tests/__init__.py
  stock_picking_operations_multilang/tests/test_stock_picking_operations_multilang.py
  stock_picking_operations_multilang/views/stock_warehouse_views.xml
Labels: needs review, approved, bot is merging ⏳

#333 [15.0][FIX] stock_picking_report_valued_sale_mrp: non existing backorder_id in stock.move
  stock_picking_report_valued_sale_mrp/models/stock_move.py
Labels: approved, bot is merging ⏳

#313 [16.0][FIX] stock_card_report: date report with timezone
  stock_card_report/reports/stock_card_report.py
  stock_card_report/tests/test_stock_card_report.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#306 [14.0][ADD] stock_quant_history: Generate stock.quant at given pasted date
  setup/stock_quant_history/odoo/addons/stock_quant_history
  setup/stock_quant_history/setup.py
  stock_quant_history/README.rst
  stock_quant_history/__init__.py
  stock_quant_history/__manifest__.py
  stock_quant_history/i18n/fr.po
  stock_quant_history/i18n/stock_quant_history.pot
  stock_quant_history/models/__init__.py
  stock_quant_history/models/stock_quant_history.py
  stock_quant_history/models/stock_quant_history_snapshot.py
  stock_quant_history/readme/CONSTRIBUTORS.rst
  stock_quant_history/readme/DESCRIPTION.rst
  stock_quant_history/readme/ROADMAP.rst
  stock_quant_history/readme/USAGE.rst
  stock_quant_history/security/ir.model.access.csv
  stock_quant_history/static/description/index.html
  stock_quant_history/tests/__init__.py
  stock_quant_history/tests/test_stock_quant_history.py
  stock_quant_history/views/stock-quant-history-snapshot.xml
  stock_quant_history/views/stock-quant-history.xml
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#335 [16.0][MIG] stock_picking_report_product_sticker: Migration to 16.0
  setup/stock_picking_report_product_sticker/odoo/addons/stock_picking_report_product_sticker
  setup/stock_picking_report_product_sticker/setup.py
  stock_picking_report_product_sticker/README.rst
  stock_picking_report_product_sticker/__init__.py
  stock_picking_report_product_sticker/__manifest__.py
  stock_picking_report_product_sticker/data/menus.xml
  stock_picking_report_product_sticker/i18n/es.po
  stock_picking_report_product_sticker/i18n/stock_picking_report_product_sticker.pot
  stock_picking_report_product_sticker/models/__init__.py
  stock_picking_report_product_sticker/models/stock_picking.py
  stock_picking_report_product_sticker/models/stock_picking_type.py
  stock_picking_report_product_sticker/readme/CONTRIBUTORS.rst
  stock_picking_report_product_sticker/readme/DESCRIPTION.rst
  stock_picking_report_product_sticker/readme/INSTALL.rst
  stock_picking_report_product_sticker/readme/USAGE.rst
  stock_picking_report_product_sticker/report/report_deliveryslip.xml
  stock_picking_report_product_sticker/static/description/icon.png
  stock_picking_report_product_sticker/static/description/index.html
  stock_picking_report_product_sticker/tests/__init__.py
  stock_picking_report_product_sticker/tests/common.py
  stock_picking_report_product_sticker/tests/test_stock_picking.py
  stock_picking_report_product_sticker/views/stock_picking_type_views.xml
  stock_picking_report_product_sticker/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳
