Repository OCA/stock-logistics-reporting, pull requests merged in 2025-03, with the labels that each got.

#375 [FIX] [16.0] stock_picking_report_product_sticker: allow stock users to print stickers
  stock_picking_report_product_sticker/models/stock_picking.py
  stock_picking_report_product_sticker/tests/common.py
Labels: needs review, approved, bot is merging ⏳

#378 [16.0][FIX] stock_account_valuation_report: Add rec_name field
  stock_account_valuation_report/wizards/stock_valuation_history.py
Labels: approved, ready to merge, bot is merging ⏳

#323 [MIG] [17.0] stock_picking_report_external_note
  stock_picking_report_external_note/README.rst
  stock_picking_report_external_note/__init__.py
  stock_picking_report_external_note/__manifest__.py
  stock_picking_report_external_note/i18n/es.po
  stock_picking_report_external_note/i18n/stock_picking_report_external_note.pot
  stock_picking_report_external_note/models/__init__.py
  stock_picking_report_external_note/models/stock_picking.py
  stock_picking_report_external_note/pyproject.toml
  stock_picking_report_external_note/readme/CONTRIBUTORS.md
  stock_picking_report_external_note/readme/DESCRIPTION.md
  stock_picking_report_external_note/readme/USAGE.md
  stock_picking_report_external_note/report/report_deliveryslip.xml
  stock_picking_report_external_note/static/description/icon.png
  stock_picking_report_external_note/static/description/icon.svg
  stock_picking_report_external_note/static/description/index.html
  stock_picking_report_external_note/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
