Repository OCA/stock-logistics-reporting, pull requests merged in 2025-06, with the labels that each got.

#394 [18.0][MIG] stock_picking_report_external_note: Migration to 18.0
  stock_picking_report_external_note/README.rst
  stock_picking_report_external_note/__init__.py
  stock_picking_report_external_note/__manifest__.py
  stock_picking_report_external_note/i18n/es.po
  stock_picking_report_external_note/i18n/it.po
  stock_picking_report_external_note/i18n/stock_picking_report_external_note.pot
  stock_picking_report_external_note/models/__init__.py
  stock_picking_report_external_note/models/stock_picking.py
  stock_picking_report_external_note/pyproject.toml
  stock_picking_report_external_note/readme/CONTRIBUTORS.md
  stock_picking_report_external_note/readme/DESCRIPTION.md
  stock_picking_report_external_note/readme/USAGE.md
  stock_picking_report_external_note/report/report_deliveryslip.xml
  stock_picking_report_external_note/static/description/icon.png
  stock_picking_report_external_note/static/description/icon.svg
  stock_picking_report_external_note/static/description/index.html
  stock_picking_report_external_note/views/stock_picking_views.xml
Labels: approved, ready to merge, merged 🎉

#405 [18.0][MIG] stock_quantity_history_location: Migration to 18.0
  stock_quantity_history_location/README.rst
  stock_quantity_history_location/__init__.py
  stock_quantity_history_location/__manifest__.py
  stock_quantity_history_location/i18n/es.po
  stock_quantity_history_location/i18n/it.po
  stock_quantity_history_location/i18n/ja.po
  stock_quantity_history_location/i18n/ro.po
  stock_quantity_history_location/i18n/stock_quantity_history_location.pot
  stock_quantity_history_location/pyproject.toml
  stock_quantity_history_location/readme/CONTRIBUTORS.md
  stock_quantity_history_location/readme/DESCRIPTION.md
  stock_quantity_history_location/readme/USAGE.md
  stock_quantity_history_location/static/description/icon.png
  stock_quantity_history_location/static/description/index.html
  stock_quantity_history_location/tests/__init__.py
  stock_quantity_history_location/tests/common.py
  stock_quantity_history_location/tests/test_stock_quantity_history_location.py
  stock_quantity_history_location/views/product_views.xml
  stock_quantity_history_location/wizards/__init__.py
  stock_quantity_history_location/wizards/stock_quantity_history.py
  stock_quantity_history_location/wizards/stock_quantity_history.xml
Labels: approved, ready to merge, bot is merging ⏳

#418 [18.0] [MIG] stock_picking_group_by_partner_by_carrier_sale_line_position: Migration to 18.0
  stock_picking_group_by_partner_by_carrier_sale_line_position/README.rst
  stock_picking_group_by_partner_by_carrier_sale_line_position/__init__.py
  stock_picking_group_by_partner_by_carrier_sale_line_position/__manifest__.py
  stock_picking_group_by_partner_by_carrier_sale_line_position/i18n/it.po
  stock_picking_group_by_partner_by_carrier_sale_line_position/i18n/stock_picking_group_by_partner_by_carrier_sale_line_position.pot
  stock_picking_group_by_partner_by_carrier_sale_line_position/models/__init__.py
  stock_picking_group_by_partner_by_carrier_sale_line_position/models/stock_picking.py
  stock_picking_group_by_partner_by_carrier_sale_line_position/pyproject.toml
  stock_picking_group_by_partner_by_carrier_sale_line_position/readme/CONTRIBUTORS.md
  stock_picking_group_by_partner_by_carrier_sale_line_position/readme/CREDITS.md
  stock_picking_group_by_partner_by_carrier_sale_line_position/readme/DESCRIPTION.md
  stock_picking_group_by_partner_by_carrier_sale_line_position/report/report_deliveryslip.xml
  stock_picking_group_by_partner_by_carrier_sale_line_position/static/description/icon.png
  stock_picking_group_by_partner_by_carrier_sale_line_position/static/description/index.html
  stock_picking_group_by_partner_by_carrier_sale_line_position/tests/__init__.py
  stock_picking_group_by_partner_by_carrier_sale_line_position/tests/test_stock_picking.py
Labels: approved, bot is merging ⏳
