Repository OCA/stock-logistics-reporting, pull requests merged in 2025-04, with the labels that each got.

#368 [MIG] stock_account_valuation_report: Migration to 18.0
  stock_account_valuation_report/README.rst
  stock_account_valuation_report/__init__.py
  stock_account_valuation_report/__manifest__.py
  stock_account_valuation_report/i18n/de.po
  stock_account_valuation_report/i18n/es.po
  stock_account_valuation_report/i18n/es_MX.po
  stock_account_valuation_report/i18n/fr.po
  stock_account_valuation_report/i18n/it.po
  stock_account_valuation_report/i18n/sl.po
  stock_account_valuation_report/i18n/stock_account_valuation_report.pot
  stock_account_valuation_report/models/__init__.py
  stock_account_valuation_report/models/account_move_line.py
  stock_account_valuation_report/models/product_product.py
  stock_account_valuation_report/pyproject.toml
  stock_account_valuation_report/readme/CONTRIBUTORS.md
  stock_account_valuation_report/readme/DESCRIPTION.md
  stock_account_valuation_report/security/ir.model.access.csv
  stock_account_valuation_report/static/description/icon.png
  stock_account_valuation_report/static/description/index.html
  stock_account_valuation_report/tests/__init__.py
  stock_account_valuation_report/tests/test_stock_account_valuation_report.py
  stock_account_valuation_report/views/product_product_views.xml
  stock_account_valuation_report/wizards/__init__.py
  stock_account_valuation_report/wizards/stock_valuation_history.py
  stock_account_valuation_report/wizards/stock_valuation_history.xml
Labels: approved, ready to merge, bot is merging ⏳

#374 [17.0][ADD] stock_move_pivot_total_price: New module stock_move_pivot_total_price
  stock_move_pivot_total_price/README.rst
  stock_move_pivot_total_price/__init__.py
  stock_move_pivot_total_price/__manifest__.py
  stock_move_pivot_total_price/hooks.py
  stock_move_pivot_total_price/i18n/ca.po
  stock_move_pivot_total_price/i18n/es.po
  stock_move_pivot_total_price/models/__init__.py
  stock_move_pivot_total_price/models/stock_move.py
  stock_move_pivot_total_price/pyproject.toml
  stock_move_pivot_total_price/readme/CONTRIBUTORS.md
  stock_move_pivot_total_price/readme/DESCRIPTION.md
  stock_move_pivot_total_price/readme/USAGE.md
  stock_move_pivot_total_price/static/description/icon.png
  stock_move_pivot_total_price/static/description/index.html
  stock_move_pivot_total_price/tests/__init__.py
  stock_move_pivot_total_price/tests/test_product_total_price.py
  stock_move_pivot_total_price/views/stock_move.xml
Labels: approved, bot is merging ⏳

#366 [18.0][MIG] stock_picking_report_valued: Migration to 18.0
  stock_picking_report_valued/README.rst
  stock_picking_report_valued/__init__.py
  stock_picking_report_valued/__manifest__.py
  stock_picking_report_valued/i18n/es.po
  stock_picking_report_valued/i18n/fr.po
  stock_picking_report_valued/i18n/fr_FR.po
  stock_picking_report_valued/i18n/hr.po
  stock_picking_report_valued/i18n/it.po
  stock_picking_report_valued/i18n/pt.po
  stock_picking_report_valued/i18n/ro.po
  stock_picking_report_valued/i18n/stock_picking_report_valued.pot
  stock_picking_report_valued/models/__init__.py
  stock_picking_report_valued/models/res_partner.py
  stock_picking_report_valued/models/stock_move_line.py
  stock_picking_report_valued/models/stock_picking.py
  stock_picking_report_valued/pyproject.toml
  stock_picking_report_valued/readme/CONFIGURE.md
  stock_picking_report_valued/readme/CONTRIBUTORS.md
  stock_picking_report_valued/readme/DESCRIPTION.md
  stock_picking_report_valued/readme/ROADMAP.md
  stock_picking_report_valued/readme/USAGE.md
  stock_picking_report_valued/report/stock_picking_report_valued.xml
  stock_picking_report_valued/static/description/icon.png
  stock_picking_report_valued/static/description/index.html
  stock_picking_report_valued/tests/__init__.py
  stock_picking_report_valued/tests/test_stock_picking_valued.py
  stock_picking_report_valued/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#403 [16.0][IMP][REF] stock_average_daily_sale: refactor
  stock_average_daily_sale/__manifest__.py
  stock_average_daily_sale/data/ir_cron.xml
  stock_average_daily_sale/demo/stock_average_daily_sale_config.xml
  stock_average_daily_sale/migrations/16.0.2.0.0/pre-migrate.py
  stock_average_daily_sale/models/__init__.py
  stock_average_daily_sale/models/stock_average_daily_sale.py
  stock_average_daily_sale/models/stock_average_daily_sale_config.py
  stock_average_daily_sale/models/stock_warehouse.py
  stock_average_daily_sale/readme/CONFIGURE.rst
  stock_average_daily_sale/readme/CONTRIBUTORS.rst
  stock_average_daily_sale/readme/DESCRIPTION.rst
  stock_average_daily_sale/readme/HISTORY.rst
  stock_average_daily_sale/readme/ROADMAP.rst
  stock_average_daily_sale/security/stock_average_daily_sale.xml
  stock_average_daily_sale/security/stock_average_daily_sale_config.xml
  stock_average_daily_sale/tests/common.py
  stock_average_daily_sale/tests/test_average_daily_sale.py
  stock_average_daily_sale/views/stock_average_daily_sale.xml
  stock_average_daily_sale/views/stock_average_daily_sale_config.xml
  stock_average_daily_sale/views/stock_warehouse.xml
Labels: approved, ready to merge, bot is merging ⏳

#410 [17.0][FIX] stock_picking_report_valued: delete reference reserved_qty
  stock_picking_report_valued/models/stock_move_line.py
Labels: bot is merging ⏳

#407 [17.0][MIG] stock_quant_history: Migration to 17.0
  stock_quant_history/README.rst
  stock_quant_history/__init__.py
  stock_quant_history/__manifest__.py
  stock_quant_history/i18n/fr.po
  stock_quant_history/i18n/it.po
  stock_quant_history/i18n/stock_quant_history.pot
  stock_quant_history/models/__init__.py
  stock_quant_history/models/stock_quant_history.py
  stock_quant_history/models/stock_quant_history_snapshot.py
  stock_quant_history/pyproject.toml
  stock_quant_history/readme/CONSTRIBUTORS.rst
  stock_quant_history/readme/DESCRIPTION.md
  stock_quant_history/readme/ROADMAP.md
  stock_quant_history/readme/USAGE.md
  stock_quant_history/security/ir.model.access.csv
  stock_quant_history/static/description/icon.png
  stock_quant_history/static/description/index.html
  stock_quant_history/tests/__init__.py
  stock_quant_history/tests/test_stock_quant_history.py
  stock_quant_history/views/stock-quant-history-snapshot.xml
  stock_quant_history/views/stock-quant-history.xml
Labels: approved, ready to merge, bot is merging ⏳
