Repository OCA/stock-logistics-reporting, pull requests merged in 2025-07, with the labels that each got.

#393 [18.0][MIG] stock_picking_report_delivery_driver: Migration to 18.0
  stock_picking_report_delivery_driver/README.rst
  stock_picking_report_delivery_driver/__init__.py
  stock_picking_report_delivery_driver/__manifest__.py
  stock_picking_report_delivery_driver/i18n/es.po
  stock_picking_report_delivery_driver/i18n/it.po
  stock_picking_report_delivery_driver/i18n/stock_picking_report_delivery_driver.pot
  stock_picking_report_delivery_driver/pyproject.toml
  stock_picking_report_delivery_driver/readme/CONTRIBUTORS.md
  stock_picking_report_delivery_driver/readme/DESCRIPTION.md
  stock_picking_report_delivery_driver/readme/USAGE.md
  stock_picking_report_delivery_driver/report/report_deliveryslip.xml
  stock_picking_report_delivery_driver/report/report_stockpicking_operations.xml
  stock_picking_report_delivery_driver/static/description/icon.png
  stock_picking_report_delivery_driver/static/description/index.html
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#424 [REF] stock_quant_history: performance improvements
  stock_quant_history/models/stock_quant_history.py
  stock_quant_history/models/stock_quant_history_snapshot.py
  stock_quant_history/security/ir.model.access.csv
Labels: approved, ready to merge, bot is merging ⏳

#392 [18.0][MIG] stock_picking_report_custom_description: Migration to 18.0
  stock_picking_report_custom_description/README.rst
  stock_picking_report_custom_description/__init__.py
  stock_picking_report_custom_description/__manifest__.py
  stock_picking_report_custom_description/i18n/es.po
  stock_picking_report_custom_description/i18n/it.po
  stock_picking_report_custom_description/i18n/stock_picking_report_custom_description.pot
  stock_picking_report_custom_description/models/__init__.py
  stock_picking_report_custom_description/models/sale_order_line.py
  stock_picking_report_custom_description/models/stock_rule.py
  stock_picking_report_custom_description/pyproject.toml
  stock_picking_report_custom_description/readme/CONTRIBUTORS.md
  stock_picking_report_custom_description/readme/DESCRIPTION.md
  stock_picking_report_custom_description/readme/USAGE.md
  stock_picking_report_custom_description/static/description/icon.png
  stock_picking_report_custom_description/static/description/index.html
  stock_picking_report_custom_description/tests/__init__.py
  stock_picking_report_custom_description/tests/test_stock_picking_report_custom_description.py
Labels: approved, bot is merging ⏳
